/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "v6.0.10-53-gef90da352"
#endif /* AVUTIL_FFVERSION_H */
